"""Initial schema with all models

Revision ID: 7a179d40ec56
Revises: 
Create Date: 2026-05-07 15:59:47.998662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a179d40ec56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake_records', sa.Column('source_plan_day_id', sa.Integer(), nullable=True))
    # Note: Foreign key constraint skipped for SQLite (requires table recreation)
    # SQLite doesn't support adding FK constraints via ALTER TABLE
    # The model still defines the FK relationship for new tables
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intake_records', type_='foreignkey')
    op.drop_column('intake_records', 'source_plan_day_id')
    # ### end Alembic commands ###
